from pathlib import Path
import re

p = Path('cafasso-wix-import/index.html')
s = p.read_text()
marker = '/* CAFASSO MOBILE APP V1 */'
css = '''
/* CAFASSO MOBILE APP V1 */
.mobile-head,.mobile-nav,.mobile-sheet{display:none}
@media(max-width:680px){
body{padding-bottom:78px;background:#F8F3EB}.shell{display:block;min-height:100vh}.side{display:none!important}
.mobile-head{display:flex;position:sticky;top:0;z-index:40;align-items:center;justify-content:space-between;gap:12px;background:linear-gradient(135deg,var(--navy),#0A2440);padding:10px 14px;min-height:66px;box-shadow:0 5px 18px rgba(10,36,64,.16)}
.mobile-brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:#fff;min-width:0}.mobile-brand img{width:34px;height:40px;object-fit:contain}.mobile-brand b{display:block;font:700 20px Georgia,serif;line-height:1}.mobile-brand small{display:block;font-size:9px;letter-spacing:.08em;opacity:.72;margin-top:4px;white-space:nowrap}.mobile-user{border:0;background:transparent;padding:0;display:flex;align-items:center;cursor:pointer}.mobile-user .avatar{width:40px;height:40px;border:2px solid rgba(255,255,255,.45);box-shadow:0 2px 8px rgba(0,0,0,.12)}
main{padding:18px 14px 26px;max-width:none}.top{margin-bottom:18px;gap:12px;align-items:center;flex-direction:row}.top h1{font-size:29px;line-height:1.08}.top p{font-size:13px;line-height:1.45}.top .pill{display:none}
.hero{padding:22px 20px;border-radius:22px;gap:16px}.hero h2{font-size:31px;line-height:1.08;margin:8px 0 10px}.hero p{font-size:14px;line-height:1.55}.quote{padding:16px;border-radius:16px}.quote strong{font-size:20px}.section{margin-top:24px}.section h3{font-size:24px;margin-bottom:12px}
.courses{grid-template-columns:1fr;gap:12px}.card{border-radius:18px;padding:17px}.course h4{font-size:18px}.course p{line-height:1.5}.course .btn{min-height:44px;padding:11px 14px}.stats{grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.stat{padding:14px;border-radius:14px;min-height:88px}.stat strong{font-size:25px;overflow-wrap:anywhere}.stat span{font-size:12px;color:var(--muted)}
.module-detail{max-width:none}.module{display:block;margin-bottom:10px}.module>div:first-child{margin-bottom:14px}.module-actions{display:grid;grid-template-columns:1fr;justify-content:stretch;gap:8px}.module-actions .badge{text-align:center}.module-actions .btn{width:100%;min-height:44px}.block h4{font-size:19px}.block-text{font-size:15px;line-height:1.65}.activity{padding:14px}.activity textarea{min-height:150px;font-size:16px}.activity-actions,.review-row,.complete-box{display:grid;grid-template-columns:1fr;align-items:stretch}.activity-actions .btn,.review-row .btn,.complete-box .btn{width:100%;min-height:46px}.module-progress{border-radius:14px;padding:13px 14px}.backline{margin-bottom:12px}.backline button{min-height:40px}
input,textarea,select,button{touch-action:manipulation}input[type=password],input[type=email],input[type=text]{font-size:16px!important;min-height:46px}
.mobile-nav{display:grid;grid-template-columns:repeat(4,1fr);position:fixed;left:0;right:0;bottom:0;z-index:60;background:rgba(255,253,249,.97);backdrop-filter:blur(14px);border-top:1px solid var(--line);padding:7px 7px calc(7px + env(safe-area-inset-bottom));box-shadow:0 -8px 24px rgba(15,45,77,.10)}.mobile-nav button{border:0;background:transparent;color:#647284;border-radius:13px;min-height:54px;padding:5px 3px;display:grid;place-items:center;gap:1px;font:700 10px Inter,system-ui;cursor:pointer}.mobile-nav button .ico{font-size:20px;line-height:1}.mobile-nav button.active{background:#FFF4CC;color:var(--navy)}
.mobile-more{position:fixed;inset:0;z-index:80;background:rgba(10,25,45,.38);display:none;align-items:flex-end;padding:14px}.mobile-more.show{display:flex}.mobile-sheet{display:block;width:100%;background:var(--card);border:1px solid var(--line);border-radius:24px;padding:10px 10px calc(10px + env(safe-area-inset-bottom));box-shadow:0 22px 70px rgba(10,25,45,.28)}.mobile-sheet-head{display:flex;align-items:center;justify-content:space-between;padding:8px 8px 12px}.mobile-sheet-head strong{font:22px Georgia,serif;color:var(--navy)}.mobile-sheet-head button{border:0;background:#F2ECE3;border-radius:50%;width:36px;height:36px;font-size:18px}.mobile-sheet a,.mobile-sheet>button:not(.close){display:flex;width:100%;align-items:center;gap:12px;text-decoration:none;border:0;background:transparent;color:var(--navy);padding:14px;border-radius:14px;font:800 14px Inter,system-ui;text-align:left}.mobile-sheet .danger{color:var(--red)}
}
'''
if marker not in s:
    s = s.replace('</style>', css + '\n</style>', 1)

new_layout = '''function layout(){document.getElementById('app').className='';document.getElementById('app').innerHTML='<div class="shell"><aside class="side"><div class="brand"><a href="./" aria-label="Volver al inicio" style="display:flex;align-items:center;gap:12px;color:inherit;text-decoration:none"><img src="'+CREST+'" alt="Maturana"><div><b>CAFASSO</b><small>Formación de Animadores</small></div></a></div><div class="nav"><button data-view="inicio"><span>Inicio</span></button><button data-view="cursos"><span>Mis cursos</span></button><button data-view="certificados"><span>Certificados</span></button><button data-view="perfil"><span>Mi perfil</span></button></div><div class="foot"><div class="motto">Caminamos juntos,<br>animamos con el corazón.</div>'+(isAdmin()?'<a href="./admin.html">Administración →</a>':'')+'<button id="logout">Cerrar sesión</button></div></aside><header class="mobile-head"><a class="mobile-brand" href="./" aria-label="Inicio CAFASSO"><img src="'+CREST+'" alt="Maturana"><div><b>CAFASSO</b><small>FORMACIÓN DE ANIMADORES</small></div></a><button class="mobile-user" data-view="perfil" aria-label="Mi perfil"><div class="avatar">'+initials(session.user.name)+'</div></button></header><main id="main"></main><nav class="mobile-nav" aria-label="Navegación principal"><button data-view="inicio"><span class="ico">⌂</span><span>Inicio</span></button><button data-view="cursos"><span class="ico">▤</span><span>Cursos</span></button><button data-view="perfil"><span class="ico">●</span><span>Perfil</span></button><button id="mobileMore"><span class="ico">•••</span><span>Más</span></button></nav><div id="mobileMoreWrap" class="mobile-more"><section class="mobile-sheet"><div class="mobile-sheet-head"><strong>Más opciones</strong><button class="close" id="mobileMoreClose" aria-label="Cerrar">×</button></div><button data-view="certificados">🏅 Certificados</button>'+(isAdmin()?'<a href="./admin.html">⚙️ Administración</a>':'')+'<button class="danger" id="mobileLogout">↪ Cerrar sesión</button></section></div></div>';Array.prototype.forEach.call(document.querySelectorAll('[data-view]'),function(b){b.onclick=function(){var w=document.getElementById('mobileMoreWrap');if(w)w.classList.remove('show');navigate(b.getAttribute('data-view'));};});document.getElementById('logout').onclick=logout;var more=document.getElementById('mobileMore'),wrap=document.getElementById('mobileMoreWrap'),close=document.getElementById('mobileMoreClose'),ml=document.getElementById('mobileLogout');if(more)more.onclick=function(){wrap.classList.add('show');};if(close)close.onclick=function(){wrap.classList.remove('show');};if(wrap)wrap.onclick=function(e){if(e.target===wrap)wrap.classList.remove('show');};if(ml)ml.onclick=logout;}'''
pat = r"function layout\(\)\{.*?\n  function top\(title,sub\)"
s2, n = re.subn(pat, new_layout + "\n  function top(title,sub)", s, count=1, flags=re.S)
if n != 1:
    raise SystemExit(f'layout patch failed: {n}')
p.write_text(s2)
